Vagrant.configure("2") do |config|
    config.vm.box="sbeliakou/centos"
    config.vm.define "lb" do |ap|
        ap.vm.provider "virtualbox" do |v|
            v.name = "lb"
            v.memory = 1024
            v.cpus = 1
        end
        ap.vm.network "private_network", ip: "192.168.56.10"
        ap.vm.hostname = "lb"
        ap.vm.provision :shell, privileged: true, path: "provisionlb.sh"
    end

    (1..2).each do |i|
        config.vm.define "node#{i}" do |tm|
            tm.vm.provider "virtualbox" do |v|
                v.name = "node#{i}"
                v.memory = 512
            end
            tm.vm.hostname = "node#{i}"
            tm.vm.network "private_network", ip: "192.168.56.#{i + 10}"
            tm.vm.synced_folder ".", "/vagrant", type: "virtualbox"
            tm.vm.provision :shell, privileged: true, path: "provision.sh"
            tm.vm.provision :shell, privileged: true, inline: <<-SHELL
                sed -i '2s/192.168.56.10/192.168.56.#{i + 10}/' /home/vagrant/nginx/conf/vhosts/backend.conf
                sed -i '4 i     add_header backend_srv node#{i};' /home/vagrant/nginx/conf/vhosts/backend.conf
                chown -R vagrant:vagrant /home/vagrant/nginx
                systemctl start nginx
            SHELL
        end
    end
end