IMAGE_NAME = "generic/centos7"

Vagrant.configure("2") do |config|

	(1..2).each do |i| 
		config.vm.define "VM#{i}" do |node|
		node.vm.box = IMAGE_NAME
		node.vm.hostname = "VM#{i}"
		node.vm.network "private_network", ip: "192.168.1.1#{i}"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "VM#{i}"
			vb.memory = "1024"
			end

		node.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		node.vm.provision "shell", path: "./files/user.sh", args: "name_surname" # Default password for login user: P@ssw0rd

		end
	end
end