IMAGE_NAME = "generic/debian10"

required_plugins = %w( vagrant-reload vagrant-vbguest )
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

Vagrant.configure("2") do |config|
    config.vm.box=IMAGE_NAME
    config.vm.define "lb" do |ap|
        ap.vm.box = "generic/centos7"
        ap.vm.provider "virtualbox" do |v|
            v.name = "lb"
            v.memory = 1024
            v.cpus = 1
        end
        ap.vm.network "private_network", ip: "192.168.1.10"
        ap.vm.hostname = "lb"
        ap.vm.provision :shell, privileged: true, path: "./files/provisiona.sh"
        ap.vm.provision :shell, privileged: true, inline: <<-SHELL
            sed -i '7s/enforcing/disabled/' /etc/selinux/config
        SHELL
        ap.vm.provision :reload
    end

    config.vm.define "tom" do |tm|
        tm.vm.provider "virtualbox" do |v|
            v.name = "tom"
            v.memory = 2048
            v.cpus = 2
        end
        tm.vm.hostname = "tom"
        tm.vm.network "private_network", ip: "192.168.1.20"
        tm.vm.provision :shell, privileged: true, path: "./files/provisiont.sh"

    end
end