IMAGE_NAME = "generic/debian10"

required_plugins = %w( vagrant-reload vagrant-vbguest )
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

Vagrant.configure("2") do |config|
    config.vm.box=IMAGE_NAME
    config.vm.define "lb" do |ap|
        ap.vm.box = "generic/centos7"
        ap.vm.provider "virtualbox" do |v|
            v.name = "lb"
            v.memory = 1024
            v.cpus = 1
        end
        ap.vm.network "private_network", ip: "192.168.1.10"
        ap.vm.hostname = "lb"
        ap.vm.provision :shell, privileged: true, path: "./files/provisiona.sh"
        ap.vm.provision :shell, privileged: true, inline: <<-SHELL
            sed -i '7s/enforcing/disabled/' /etc/selinux/config
        SHELL
        ap.vm.provision :reload
    end

    (1..3).each do |i|
        config.vm.define "tom#{i}" do |tm|
            tm.vm.provider "virtualbox" do |v|
                v.name = "tom#{i}"
                v.memory = 512
            end
            tm.vm.hostname = "tom#{i}"
            tm.vm.network "private_network", ip: "192.168.1.#{i + 20}"
            tm.vm.synced_folder ".", "/vagrant", type: "virtualbox"
            tm.vm.provision :shell, privileged: true, path: "./files/provisiont.sh"
            tm.vm.provision :shell, privileged: true, inline: <<-SHELL
                sed -i '22s/port="8005"/port="8#{i}05"/' /opt/tomcat/conf/server.xml
                sed -i '68s/port="8080"/port="808#{i}"/' /opt/tomcat/conf/server.xml
                sed -i '103s/port="8009"/port="8#{i}09"/' /opt/tomcat/conf/server.xml
                sed -i '114s/defaultHost="localhost"/defaultHost="localhost" jvmRoute="tom#{i}"/' /opt/tomcat/conf/server.xml
                sed -i '122 i <Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster"/>' /opt/tomcat/conf/server.xml
                cp -a /vagrant/files/clusterjsp /opt/tomcat/webapps/
                chown -R tomcat /opt/tomcat/webapps/
            SHELL
        end
    end
end