Vagrant.configure("2") do |config|
    config.vm.box = "ivan_balandzin/mntlab-troubleshooting"
    config.vm.define "tst" do |ap|
        ap.vm.provider "virtualbox" do |v|
            v.name = "tst"
            v.memory = 1024
            v.cpus = 1
        end
        ap.vm.network "private_network", ip: "192.168.56.20"
        ap.vm.hostname = "tst"
        ap.vm.provision :shell, privileged: true, path: "fix.sh"
    end
end
