IMAGE_NAME = "sbeliakou/centos"
HOSTNAME = "web"

Vagrant.configure("2") do |config|

	config.vm.define HOSTNAME do |master|
		master.vm.provider "virtualbox" do |v|
			v.name = HOSTNAME
			v.memory = 2048
			v.cpus = 2
		end
		master.vm.box = IMAGE_NAME
		master.vm.network "private_network", ip: "192.168.56.10"
		master.vm.hostname = HOSTNAME
		master.vm.provision :shell, privileged: true, path: "provision.sh"
	end
end